spring.application.name=NotificationService

server.port=8081
server.servlet.context-path=/notification

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Single Sender
notification.mail.from=your-email@gmail.com

# SWAGGER
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# EMAIL TEMPLATE DEFAULTS
notification.template.app-name=Notification Service
notification.template.tagline=Reliable & Secure Communication
notification.template.team-name=Notification Team
notification.template.company-name=ABC Company
notification.template.footer-message=If you have any questions, feel free to contact us.

# LOGO CONFIG
notification.template.logo-path=static/logo/logo.jpg
notification.template.logo-content-type=image/avif



